site_name: VSCode Class 2026
site_author: Adam Catching

theme:
  name: readthedocs 
  features:
    - navigation.indexes
nav:
  - 0. Introduction: https://vscode-class-2026.readthedocs.io/
  - 1. Biowulf: https://vscode-class-2026.readthedocs.io/biowulf/
  - 2. VSCode: https://vscode-class-2026.readthedocs.io/vscode/
  - 3. Anaconda: https://vscode-class-2026.readthedocs.io/anaconda/
  - 4. Python: https://vscode-class-2026.readthedocs.io/python_intro/
  - 5. GitHub: https://vscode-class-2026.readthedocs.io/github/
  - 6. Snakemake: https://vscode-class-2026.readthedocs.io/snakemake/
  - 7. Singularity: https://vscode-class-2026.readthedocs.io/singularity_page/