site_name: VSCode Class 2026
site_author: Adam Catching

repo_url: https://github.com/adamcatching/VSCode_class_2026

theme:
  name: readthedocs 
  features:
    - navigation.indexes
nav:
  - Introduction: https://vscode-class-2026.readthedocs.io/docs/index.md
  - Biowulf: https://vscode-class-2026.readthedocs.io/docs/biowulf.md
  - VSCode: https://vscode-class-2026.readthedocs.io/docs/vscode.md
  - Python: https://vscode-class-2026.readthedocs.io/docs/python.md
  - GitHub: https://vscode-class-2026.readthedocs.io/docs/github.md
  - Snakemake: https://vscode-class-2026.readthedocs.io/docs/snakemake.md
  - Singularity: https://vscode-class-2026.readthedocs.io/docs/singularity.md