site_name: VSCode Class 2026
site_author: Adam Catching

theme:
  name: readthedocs 
  features:
    - navigation.indexes
nav:
  - Introduction: https://vscode-class-2026.readthedocs.io/
  - Biowulf: https://vscode-class-2026.readthedocs.io/biowulf/
  - VSCode: https://vscode-class-2026.readthedocs.io/vscode/
  - Python: https://vscode-class-2026.readthedocs.io/python_intro.ipynb/
  - GitHub: https://vscode-class-2026.readthedocs.io/github/
  - Snakemake: https://vscode-class-2026.readthedocs.io/snakemake/
  - Singularity: https://vscode-class-2026.readthedocs.io/singularity/
plugins:
  - mkdocs-jupyter