site_name: VSCode Class 2026
site_author: Adam Catching

repo_url: https://github.com/adamcatching/VSCode_class_2026

theme:
  name: readthedocs # The default theme
  # Or use a popular third-party theme like 'material'
  # name: material

nav:
  - Home: docs/index.md
  - Biowulf: docs/biowulf.md
  - VSCode: docs/vscode.md
  - Python: docs/python.md
  - GitHub: docs/github.md
  - Snakemake: docs/snakemake.md
  - Singularity: docs/singularity.md