site_name: VSCode Class 2026
site_author: Adam Catching

repo_url: https://github.com/adamcatching/VSCode_class_2026

theme:
  name: readthedocs 
  features:
    - navigation.indexes
nav:
  - Biowulf: biowulf.md
  - VSCode: vscode.md
  - Python: python.md
  - GitHub: github.md
  - Snakemake: snakemake.md
  - Singularity: singularity.md