site_name: VSCode Class 2026
site_author: Adam Catching

theme:
  name: readthedocs 
  features:
    - navigation.indexes
nav:
  - Introduction: https://vscode-class-2026.readthedocs.io/
  - Biowulf: https://vscode-class-2026.readthedocs.io/biowulf/
  - VSCode: https://vscode-class-2026.readthedocs.io/vscode.md/
  - Python: https://vscode-class-2026.readthedocs.io/python.md/
  - GitHub: https://vscode-class-2026.readthedocs.io/github.md/
  - Snakemake: https://vscode-class-2026.readthedocs.io/snakemake.md/
  - Singularity: https://vscode-class-2026.readthedocs.io/singularity.md/